<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>PortalTestSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient>gxu@guardanthealth.com;</mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>986f512e-9c12-4945-8bd9-450baf27afe6</testSuiteGuid>
   <testCaseLink>
      <guid>785cda28-f847-4ff2-ada6-628b3fb0b772</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PORTAL/PortalLogin</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>43148f9c-55f3-4207-aa4d-1d79b04bd6ef</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestAccounts</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>43148f9c-55f3-4207-aa4d-1d79b04bd6ef</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>77226284-0ba3-44dc-be23-ec0c419fc8b3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>43148f9c-55f3-4207-aa4d-1d79b04bd6ef</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>01cd34d4-5db6-4d14-a157-71c89c7e33e0</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
