<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_TB Review BIP DataLD Re</name>
   <tag></tag>
   <elementGuidId>461f2049-06ba-499b-b6bd-ab177fae7ff1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;pr0_u_ghrequeststatus&quot;)[count(. | //select[@id = 'pr0_u_ghrequeststatus' and @ref_element = 'Object Repository/LIMS/DCO/Reporting/Page_All Requests/iframe_Your browser does not s' and @ref_element_is_shadow_root = 'true']) = count(//select[@id = 'pr0_u_ghrequeststatus' and @ref_element = 'Object Repository/LIMS/DCO/Reporting/Page_All Requests/iframe_Your browser does not s' and @ref_element_is_shadow_root = 'true'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pr0_u_ghrequeststatus</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pr0_u_ghrequeststatus</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>60</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>sdiSetRowUpdate(event)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>sdiSetRowUpdate(event)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TB Review BIP DataLD Review BIP DataCLS Review and Release ReportBioinformatics ReviewLIMS SupportRedo SamplesReleasedPending Queue</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr0_u_ghrequeststatus&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/LIMS/DCO/Reporting/Page_All Requests/iframe_Your browser does not s</value>
   </webElementProperties>
</WebElementEntity>
