<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_OK</name>
   <tag></tag>
   <elementGuidId>657fa52e-f075-4ac4-bd05-c33c787fdbce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;argsdiv_GHDV2Search&quot;)/fieldset[@class=&quot;search_fieldset&quot;]/table[@class=&quot;search_queryargtable&quot;]/tbody[1]/tr[3]/td[1]/button[@class=&quot;button_smalltext&quot;]/table[1]/tbody[1]/tr[1]/td[1][count(. | //td[(text() = 'OK' or . = 'OK')]) = count(//td[(text() = 'OK' or . = 'OK')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;argsdiv_GHDV2Search&quot;]//td[text()='OK']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valign</name>
      <type>Main</type>
      <value>middle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>center</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;argsdiv_GHDV2Search&quot;)/fieldset[@class=&quot;search_fieldset&quot;]/table[@class=&quot;search_queryargtable&quot;]/tbody[1]/tr[3]/td[1]/button[@class=&quot;button_smalltext&quot;]/table[1]/tbody[1]/tr[1]/td[1]</value>
   </webElementProperties>
</WebElementEntity>
