<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_R08</name>
   <tag></tag>
   <elementGuidId>d7dc31a6-7738-480e-b7d5-a8fad1a177f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;fotable&quot;)/tbody[1]/tr[@id=&quot;R08&quot;]/td[@id=&quot;notselected&quot;]/input[@id=&quot;R08&quot;][count(. | //input[@type = 'checkbox' and @name = 'R08' and @id = 'R08']) = count(//input[@type = 'checkbox' and @name = 'R08' and @id = 'R08'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>R08</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>R08</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>test(this.checked,this.id);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fotable&quot;)/tbody[1]/tr[@id=&quot;R08&quot;]/td[@id=&quot;notselected&quot;]/input[@id=&quot;R08&quot;]</value>
   </webElementProperties>
</WebElementEntity>
